import json
import sys
from pathlib import Path

# Add project root to sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend.database import SessionLocal, init_db
from backend.models.weapon import Weapon
from backend.models.user import User
from backend.models.player import Player
from backend.models.loadout import Loadout
from backend.services.auth_service import hash_password

WEAPONS_CATALOG = [
    # 1. ASSAULT RIFLES (10)
    {
        "id": "ar_astra4",
        "name": "ASTRA-AR4",
        "category": "ASSAULT_RIFLE",
        "damage": 28,
        "fire_rate": 0.095,
        "range_stat": 65,
        "accuracy": 72,
        "mobility": 68,
        "recoil": 54,
        "magazine_size": 30,
        "reload_time": 1.45,
        "ads_speed": 0.24,
        "unlock_level": 1,
        "tier": "COMMON",
        "description": "Balanced architectural blueprint assault rifle. High rate of fire and low muzzle rise.",
        "attachments": ["iron", "reddot", "holo", "compensator", "vertical_grip", "extended_mag"],
        "skins": ["Classic Blue", "Charcoal Graphite", "Crimson Rebel"]
    },
    {
        "id": "ar_vector_c",
        "name": "Vector-Carbine",
        "category": "ASSAULT_RIFLE",
        "damage": 26,
        "fire_rate": 0.082,
        "range_stat": 60,
        "accuracy": 76,
        "mobility": 72,
        "recoil": 48,
        "magazine_size": 32,
        "reload_time": 1.35,
        "ads_speed": 0.22,
        "unlock_level": 4,
        "tier": "RARE",
        "description": "Rapid response tactical carbine engineered for fluid room clearing.",
        "attachments": ["reddot", "holo", "suppressor", "angled_grip", "laser_sight"],
        "skins": ["Classic Blue", "Cyber Gold", "Neon Grid"]
    },
    {
        "id": "ar_m4_blueprint",
        "name": "Blueprint M4-X",
        "category": "ASSAULT_RIFLE",
        "damage": 30,
        "fire_rate": 0.102,
        "range_stat": 70,
        "accuracy": 78,
        "mobility": 65,
        "recoil": 50,
        "magazine_size": 30,
        "reload_time": 1.5,
        "ads_speed": 0.25,
        "unlock_level": 8,
        "tier": "RARE",
        "description": "Standard military issue blueprint platform with exceptional mid-range stability.",
        "attachments": ["iron", "reddot", "holo", "scope4x", "compensator", "drum_mag"],
        "skins": ["Classic Blue", "Royal Violet", "Sepia Parchment"]
    },
    {
        "id": "ar_apex_x",
        "name": "Apex-X Battle Rifle",
        "category": "ASSAULT_RIFLE",
        "damage": 35,
        "fire_rate": 0.125,
        "range_stat": 78,
        "accuracy": 82,
        "mobility": 58,
        "recoil": 62,
        "magazine_size": 25,
        "reload_time": 1.65,
        "ads_speed": 0.28,
        "unlock_level": 14,
        "tier": "EPIC",
        "description": "Heavy 7.62mm caliber rifle delivering devastating stopping power per burst.",
        "attachments": ["holo", "scope4x", "compensator", "bipod", "extended_mag"],
        "skins": ["Crimson Rebel", "Cyber Gold"]
    },
    {
        "id": "ar_ronin7",
        "name": "Ronin-7 Bullpup",
        "category": "ASSAULT_RIFLE",
        "damage": 29,
        "fire_rate": 0.088,
        "range_stat": 66,
        "accuracy": 74,
        "mobility": 75,
        "recoil": 52,
        "magazine_size": 30,
        "reload_time": 1.4,
        "ads_speed": 0.21,
        "unlock_level": 20,
        "tier": "EPIC",
        "description": "Compact bullpup architecture with superior corner-peeking handling speed.",
        "attachments": ["reddot", "holo", "laser_sight", "vertical_grip"],
        "skins": ["Neon Grid", "Charcoal Graphite"]
    },
    {
        "id": "ar_kestrel24",
        "name": "Kestrel-24",
        "category": "ASSAULT_RIFLE",
        "damage": 27,
        "fire_rate": 0.078,
        "range_stat": 62,
        "accuracy": 68,
        "mobility": 78,
        "recoil": 58,
        "magazine_size": 35,
        "reload_time": 1.38,
        "ads_speed": 0.20,
        "unlock_level": 26,
        "tier": "RARE",
        "description": "Hyper-cadence rifle designed to overwhelm hostile fireteams at close range.",
        "attachments": ["reddot", "suppressor", "extended_mag", "angled_grip"],
        "skins": ["Classic Blue", "Crimson Rebel"]
    },
    {
        "id": "ar_phantom556",
        "name": "Phantom-556 Stealth",
        "category": "ASSAULT_RIFLE",
        "damage": 31,
        "fire_rate": 0.098,
        "range_stat": 72,
        "accuracy": 80,
        "mobility": 66,
        "recoil": 44,
        "magazine_size": 30,
        "reload_time": 1.48,
        "ads_speed": 0.23,
        "unlock_level": 32,
        "tier": "LEGENDARY",
        "description": "Integrated suppressed barrel with subsonic ink rounds for ghost operations.",
        "attachments": ["holo", "scope4x", "vertical_grip", "laser_sight"],
        "skins": ["Charcoal Graphite", "Royal Violet", "Cyber Gold"]
    },
    {
        "id": "ar_vanguard11",
        "name": "Vanguard-11",
        "category": "ASSAULT_RIFLE",
        "damage": 33,
        "fire_rate": 0.110,
        "range_stat": 75,
        "accuracy": 84,
        "mobility": 62,
        "recoil": 56,
        "magazine_size": 28,
        "reload_time": 1.55,
        "ads_speed": 0.26,
        "unlock_level": 38,
        "tier": "EPIC",
        "description": "Precision marksman-hybrid assault rifle built for long-line corridor control.",
        "attachments": ["scope4x", "compensator", "extended_mag", "bipod"],
        "skins": ["Sepia Parchment", "Classic Blue"]
    },
    {
        "id": "ar_nomad_a1",
        "name": "Nomad-A1 Tactical",
        "category": "ASSAULT_RIFLE",
        "damage": 30,
        "fire_rate": 0.094,
        "range_stat": 68,
        "accuracy": 75,
        "mobility": 70,
        "recoil": 50,
        "magazine_size": 30,
        "reload_time": 1.42,
        "ads_speed": 0.23,
        "unlock_level": 44,
        "tier": "LEGENDARY",
        "description": "Ruggedized desert blueprint variant adapted for harsh frontline arena conditions.",
        "attachments": ["reddot", "holo", "compensator", "drum_mag"],
        "skins": ["Sepia Parchment", "Neon Grid"]
    },
    {
        "id": "ar_sovereign_r",
        "name": "Sovereign-R Blueprint",
        "category": "ASSAULT_RIFLE",
        "damage": 34,
        "fire_rate": 0.090,
        "range_stat": 80,
        "accuracy": 86,
        "mobility": 64,
        "recoil": 46,
        "magazine_size": 35,
        "reload_time": 1.5,
        "ads_speed": 0.22,
        "unlock_level": 50,
        "tier": "BLUEPRINT",
        "description": "Masterwork blueprint assault rifle hand-inked with gold technical schematics.",
        "attachments": ["scope4x", "holo", "suppressor", "vertical_grip", "drum_mag"],
        "skins": ["Cyber Gold", "Royal Violet"]
    },

    # 2. SUBMACHINE GUNS (8)
    {
        "id": "smg_cypher9",
        "name": "Cypher-9",
        "category": "SMG",
        "damage": 22,
        "fire_rate": 0.065,
        "range_stat": 42,
        "accuracy": 64,
        "mobility": 88,
        "recoil": 42,
        "magazine_size": 34,
        "reload_time": 1.15,
        "ads_speed": 0.16,
        "unlock_level": 1,
        "tier": "COMMON",
        "description": "High-mobility 9mm submachine gun engineered for frantic close-quarters duels.",
        "attachments": ["iron", "reddot", "suppressor", "laser_sight", "extended_mag"],
        "skins": ["Classic Blue", "Charcoal Graphite"]
    },
    {
        "id": "smg_striker_x",
        "name": "Striker-X",
        "category": "SMG",
        "damage": 24,
        "fire_rate": 0.072,
        "range_stat": 46,
        "accuracy": 66,
        "mobility": 85,
        "recoil": 45,
        "magazine_size": 30,
        "reload_time": 1.2,
        "ads_speed": 0.17,
        "unlock_level": 6,
        "tier": "RARE",
        "description": "Reliable sub-gun with consistent vertical climb and fast sprint-to-fire transition.",
        "attachments": ["reddot", "compensator", "angled_grip", "extended_mag"],
        "skins": ["Crimson Rebel", "Classic Blue"]
    },
    {
        "id": "smg_razor45",
        "name": "Razor-45 Heavy SMG",
        "category": "SMG",
        "damage": 28,
        "fire_rate": 0.085,
        "range_stat": 52,
        "accuracy": 72,
        "mobility": 80,
        "recoil": 54,
        "magazine_size": 25,
        "reload_time": 1.3,
        "ads_speed": 0.19,
        "unlock_level": 12,
        "tier": "RARE",
        "description": "Chambered in heavy .45 ACP with lethal punch within 15 meters.",
        "attachments": ["holo", "suppressor", "vertical_grip", "extended_mag"],
        "skins": ["Charcoal Graphite", "Sepia Parchment"]
    },
    {
        "id": "smg_pulse99",
        "name": "Pulse-SMG 99",
        "category": "SMG",
        "damage": 20,
        "fire_rate": 0.055,
        "range_stat": 38,
        "accuracy": 60,
        "mobility": 92,
        "recoil": 48,
        "magazine_size": 40,
        "reload_time": 1.1,
        "ads_speed": 0.15,
        "unlock_level": 18,
        "tier": "EPIC",
        "description": "Blistering cyclic rate shredding enemy armor before hostiles can ADS.",
        "attachments": ["reddot", "laser_sight", "extended_mag"],
        "skins": ["Neon Grid", "Cyber Gold"]
    },
    {
        "id": "smg_echo9",
        "name": "Echo-9 PDW",
        "category": "SMG",
        "damage": 23,
        "fire_rate": 0.068,
        "range_stat": 45,
        "accuracy": 68,
        "mobility": 86,
        "recoil": 40,
        "magazine_size": 32,
        "reload_time": 1.22,
        "ads_speed": 0.18,
        "unlock_level": 24,
        "tier": "RARE",
        "description": "Personal defense weapon with top-rail optic mounting and side-loading magazine.",
        "attachments": ["reddot", "holo", "suppressor", "angled_grip"],
        "skins": ["Classic Blue", "Royal Violet"]
    },
    {
        "id": "smg_viper_c",
        "name": "Viper-Compact",
        "category": "SMG",
        "damage": 25,
        "fire_rate": 0.075,
        "range_stat": 48,
        "accuracy": 70,
        "mobility": 87,
        "recoil": 43,
        "magazine_size": 28,
        "reload_time": 1.18,
        "ads_speed": 0.16,
        "unlock_level": 30,
        "tier": "EPIC",
        "description": "Foldable wire stock and ergonomic fore-contour for aggressive mobile sliding.",
        "attachments": ["reddot", "laser_sight", "compensator", "drum_mag"],
        "skins": ["Crimson Rebel", "Neon Grid"]
    },
    {
        "id": "smg_stinger7",
        "name": "Stinger-7 AP",
        "category": "SMG",
        "damage": 26,
        "fire_rate": 0.070,
        "range_stat": 54,
        "accuracy": 74,
        "mobility": 84,
        "recoil": 46,
        "magazine_size": 30,
        "reload_time": 1.25,
        "ads_speed": 0.18,
        "unlock_level": 36,
        "tier": "LEGENDARY",
        "description": "Armor-piercing blueprint submachine gun tuned for defensive objective retakes.",
        "attachments": ["holo", "scope4x", "suppressor", "vertical_grip"],
        "skins": ["Cyber Gold", "Charcoal Graphite"]
    },
    {
        "id": "smg_spectre10",
        "name": "Spectre-10 Master",
        "category": "SMG",
        "damage": 27,
        "fire_rate": 0.062,
        "range_stat": 50,
        "accuracy": 76,
        "mobility": 90,
        "recoil": 38,
        "magazine_size": 36,
        "reload_time": 1.12,
        "ads_speed": 0.14,
        "unlock_level": 48,
        "tier": "BLUEPRINT",
        "description": "Tournament-grade SMG blueprint with zero horizontal drift and custom trigger.",
        "attachments": ["reddot", "laser_sight", "suppressor", "drum_mag"],
        "skins": ["Cyber Gold", "Royal Violet"]
    },

    # 3. SHOTGUNS (6)
    {
        "id": "sg_trench12",
        "name": "Trench-12 Pump",
        "category": "SHOTGUN",
        "damage": 18, # x8 pellets = 144 max
        "fire_rate": 0.75,
        "range_stat": 28,
        "accuracy": 45,
        "mobility": 65,
        "recoil": 75,
        "magazine_size": 6,
        "reload_time": 1.8,
        "ads_speed": 0.28,
        "unlock_level": 1,
        "tier": "COMMON",
        "description": "Raw, heavy pump-action tactical shotgun. Lethal single blast inside 8 meters.",
        "attachments": ["choke", "laser_sight", "extended_tube"],
        "skins": ["Classic Blue", "Sepia Parchment"]
    },
    {
        "id": "sg_breacher870",
        "name": "Breacher-870",
        "category": "SHOTGUN",
        "damage": 20, # x8 pellets = 160 max
        "fire_rate": 0.85,
        "range_stat": 32,
        "accuracy": 50,
        "mobility": 62,
        "recoil": 80,
        "magazine_size": 7,
        "reload_time": 2.0,
        "ads_speed": 0.30,
        "unlock_level": 10,
        "tier": "RARE",
        "description": "Reinforced steel receiver delivering wider pellet spread for doorway assaults.",
        "attachments": ["choke", "reddot", "laser_sight"],
        "skins": ["Charcoal Graphite", "Crimson Rebel"]
    },
    {
        "id": "sg_citadel_semi",
        "name": "Citadel Semi-Auto",
        "category": "SHOTGUN",
        "damage": 14, # x8 pellets = 112 max
        "fire_rate": 0.35,
        "range_stat": 30,
        "accuracy": 48,
        "mobility": 60,
        "recoil": 68,
        "magazine_size": 8,
        "reload_time": 2.2,
        "ads_speed": 0.26,
        "unlock_level": 16,
        "tier": "EPIC",
        "description": "Gas-operated semi-automatic shotgun allowing rapid follow-up hammer blows.",
        "attachments": ["reddot", "holo", "extended_mag", "compensator"],
        "skins": ["Neon Grid", "Cyber Gold"]
    },
    {
        "id": "sg_havoc_drum",
        "name": "Havoc-12 Drum",
        "category": "SHOTGUN",
        "damage": 12, # x8 pellets = 96 max
        "fire_rate": 0.28,
        "range_stat": 26,
        "accuracy": 42,
        "mobility": 54,
        "recoil": 72,
        "magazine_size": 20,
        "reload_time": 2.8,
        "ads_speed": 0.32,
        "unlock_level": 28,
        "tier": "EPIC",
        "description": "Massive 20-round rotary drum shotgun engineered for non-stop breach suppression.",
        "attachments": ["laser_sight", "vertical_grip", "holo"],
        "skins": ["Crimson Rebel", "Classic Blue"]
    },
    {
        "id": "sg_enforcer_db",
        "name": "Enforcer Double-Barrel",
        "category": "SHOTGUN",
        "damage": 24, # x8 pellets = 192 max
        "fire_rate": 0.20,
        "range_stat": 25,
        "accuracy": 52,
        "mobility": 72,
        "recoil": 85,
        "magazine_size": 2,
        "reload_time": 1.5,
        "ads_speed": 0.22,
        "unlock_level": 34,
        "tier": "LEGENDARY",
        "description": "Twin break-action barrels discharging immediate devastating dual buckshot.",
        "attachments": ["sawed_off_stock", "tight_choke"],
        "skins": ["Sepia Parchment", "Royal Violet"]
    },
    {
        "id": "sg_bulldog12g",
        "name": "Bulldog-12G Master",
        "category": "SHOTGUN",
        "damage": 17, # x8 pellets = 136 max
        "fire_rate": 0.45,
        "range_stat": 36,
        "accuracy": 58,
        "mobility": 66,
        "recoil": 64,
        "magazine_size": 10,
        "reload_time": 1.9,
        "ads_speed": 0.24,
        "unlock_level": 46,
        "tier": "BLUEPRINT",
        "description": "Blueprint combat shotgun with rifled choke tightening long-hallway pellet clusters.",
        "attachments": ["rifled_choke", "reddot", "extended_mag", "vertical_grip"],
        "skins": ["Cyber Gold", "Classic Blue"]
    },

    # 4. LIGHT MACHINE GUNS (6)
    {
        "id": "lmg_titan100",
        "name": "Titan-100 LMG",
        "category": "LMG",
        "damage": 32,
        "fire_rate": 0.115,
        "range_stat": 75,
        "accuracy": 68,
        "mobility": 45,
        "recoil": 65,
        "magazine_size": 100,
        "reload_time": 4.2,
        "ads_speed": 0.38,
        "unlock_level": 5,
        "tier": "COMMON",
        "description": "Continuous suppressive fire platform holding down choke points and objective zones.",
        "attachments": ["holo", "scope4x", "bipod", "compensator"],
        "skins": ["Classic Blue", "Charcoal Graphite"]
    },
    {
        "id": "lmg_bastion_belt",
        "name": "Bastion-75 Belt",
        "category": "LMG",
        "damage": 34,
        "fire_rate": 0.125,
        "range_stat": 80,
        "accuracy": 72,
        "mobility": 42,
        "recoil": 62,
        "magazine_size": 75,
        "reload_time": 3.8,
        "ads_speed": 0.36,
        "unlock_level": 15,
        "tier": "RARE",
        "description": "High-caliber belt-fed machine gun with predictable vertical recoil climb.",
        "attachments": ["scope4x", "bipod", "flash_hider"],
        "skins": ["Sepia Parchment", "Crimson Rebel"]
    },
    {
        "id": "lmg_ironclad_mg",
        "name": "Ironclad-MG",
        "category": "LMG",
        "damage": 30,
        "fire_rate": 0.095,
        "range_stat": 74,
        "accuracy": 66,
        "mobility": 48,
        "recoil": 58,
        "magazine_size": 120,
        "reload_time": 4.5,
        "ads_speed": 0.40,
        "unlock_level": 22,
        "tier": "EPIC",
        "description": "Enormous ammunition capacity designed to eliminate entire respawn waves.",
        "attachments": ["reddot", "holo", "vertical_grip", "bipod"],
        "skins": ["Neon Grid", "Cyber Gold"]
    },
    {
        "id": "lmg_devastator",
        "name": "Devastator-762",
        "category": "LMG",
        "damage": 36,
        "fire_rate": 0.135,
        "range_stat": 82,
        "accuracy": 75,
        "mobility": 40,
        "recoil": 70,
        "magazine_size": 60,
        "reload_time": 3.5,
        "ads_speed": 0.35,
        "unlock_level": 29,
        "tier": "EPIC",
        "description": "Punchy 7.62mm rounds punching straight through wooden barricades and light cover.",
        "attachments": ["scope4x", "compensator", "bipod"],
        "skins": ["Charcoal Graphite", "Classic Blue"]
    },
    {
        "id": "lmg_fortress50",
        "name": "Fortress-50 Heavy",
        "category": "LMG",
        "damage": 38,
        "fire_rate": 0.145,
        "range_stat": 85,
        "accuracy": 78,
        "mobility": 38,
        "recoil": 74,
        "magazine_size": 80,
        "reload_time": 4.0,
        "ads_speed": 0.42,
        "unlock_level": 40,
        "tier": "LEGENDARY",
        "description": "Monolithic defensive support firearm built for fortification holding.",
        "attachments": ["scope4x", "bipod", "heavy_compensator"],
        "skins": ["Royal Violet", "Cyber Gold"]
    },
    {
        "id": "lmg_rampart88",
        "name": "Rampart-88 Blueprint",
        "category": "LMG",
        "damage": 35,
        "fire_rate": 0.108,
        "range_stat": 86,
        "accuracy": 82,
        "mobility": 46,
        "recoil": 54,
        "magazine_size": 100,
        "reload_time": 3.6,
        "ads_speed": 0.34,
        "unlock_level": 49,
        "tier": "BLUEPRINT",
        "description": "Balanced masterwork light machine gun with stabilized blueprint barrel shroud.",
        "attachments": ["scope4x", "holo", "vertical_grip", "bipod"],
        "skins": ["Cyber Gold", "Classic Blue"]
    },

    # 5. MARKSMAN & SNIPER RIFLES (8)
    {
        "id": "sr_marksman_bolt",
        "name": "Marksman Bolt Sniper",
        "category": "SNIPER",
        "damage": 130,
        "fire_rate": 1.25,
        "range_stat": 92,
        "accuracy": 94,
        "mobility": 45,
        "recoil": 78,
        "magazine_size": 5,
        "reload_time": 2.2,
        "ads_speed": 0.38,
        "unlock_level": 2,
        "tier": "COMMON",
        "description": "Classic bolt-action blueprint marksman rifle. 1-shot lethal headshot across map.",
        "attachments": ["scope4x", "scope8x", "bipod", "suppressor"],
        "skins": ["Classic Blue", "Sepia Parchment"]
    },
    {
        "id": "sr_longbow50",
        "name": "Longbow-50 Anti-Material",
        "category": "SNIPER",
        "damage": 150,
        "fire_rate": 1.45,
        "range_stat": 98,
        "accuracy": 96,
        "mobility": 38,
        "recoil": 88,
        "magazine_size": 5,
        "reload_time": 2.6,
        "ads_speed": 0.44,
        "unlock_level": 11,
        "tier": "RARE",
        "description": "Massive .50 BMG round terminating targets through torso hits inside 40 meters.",
        "attachments": ["scope8x", "bipod", "heavy_muzzle_brake"],
        "skins": ["Charcoal Graphite", "Crimson Rebel"]
    },
    {
        "id": "sr_valkyrie_dmr",
        "name": "Valkyrie DMR Semi",
        "category": "SNIPER",
        "damage": 68,
        "fire_rate": 0.32,
        "range_stat": 84,
        "accuracy": 88,
        "mobility": 58,
        "recoil": 58,
        "magazine_size": 12,
        "reload_time": 1.7,
        "ads_speed": 0.28,
        "unlock_level": 17,
        "tier": "RARE",
        "description": "Semi-automatic designated marksman rifle offering lethal double-taps at medium range.",
        "attachments": ["holo", "scope4x", "suppressor", "vertical_grip", "extended_mag"],
        "skins": ["Classic Blue", "Neon Grid"]
    },
    {
        "id": "sr_horizon308",
        "name": "Horizon-308",
        "category": "SNIPER",
        "damage": 125,
        "fire_rate": 1.15,
        "range_stat": 90,
        "accuracy": 92,
        "mobility": 48,
        "recoil": 72,
        "magazine_size": 6,
        "reload_time": 2.1,
        "ads_speed": 0.35,
        "unlock_level": 23,
        "tier": "EPIC",
        "description": "Sleek carbon composite chassis with faster cycle time for aggressive quick-scopers.",
        "attachments": ["scope4x", "scope8x", "angled_grip"],
        "skins": ["Neon Grid", "Cyber Gold"]
    },
    {
        "id": "sr_ghost408",
        "name": "Ghost-408 CheyTac",
        "category": "SNIPER",
        "damage": 140,
        "fire_rate": 1.35,
        "range_stat": 96,
        "accuracy": 98,
        "mobility": 42,
        "recoil": 82,
        "magazine_size": 5,
        "reload_time": 2.4,
        "ads_speed": 0.40,
        "unlock_level": 31,
        "tier": "LEGENDARY",
        "description": "Extreme long-range ballistic trajectory with virtually zero windage deflection.",
        "attachments": ["scope8x", "suppressor", "bipod"],
        "skins": ["Royal Violet", "Charcoal Graphite"]
    },
    {
        "id": "sr_eclipse_dmr",
        "name": "Eclipse-DMR Fast",
        "category": "SNIPER",
        "damage": 72,
        "fire_rate": 0.28,
        "range_stat": 82,
        "accuracy": 86,
        "mobility": 62,
        "recoil": 54,
        "magazine_size": 15,
        "reload_time": 1.6,
        "ads_speed": 0.25,
        "unlock_level": 37,
        "tier": "EPIC",
        "description": "High-mobility tactical DMR for agile perimeter patrolling and team support.",
        "attachments": ["reddot", "scope4x", "compensator", "drum_mag"],
        "skins": ["Crimson Rebel", "Sepia Parchment"]
    },
    {
        "id": "sr_sentinel_m",
        "name": "Sentinel-M Precision",
        "category": "SNIPER",
        "damage": 135,
        "fire_rate": 1.20,
        "range_stat": 95,
        "accuracy": 97,
        "mobility": 46,
        "recoil": 75,
        "magazine_size": 7,
        "reload_time": 2.2,
        "ads_speed": 0.34,
        "unlock_level": 43,
        "tier": "LEGENDARY",
        "description": "Match-grade match rifle with tuned two-stage trigger and fluted blueprint barrel.",
        "attachments": ["scope8x", "compensator", "extended_mag"],
        "skins": ["Cyber Gold", "Classic Blue"]
    },
    {
        "id": "sr_whisper762",
        "name": "Whisper-762 Master",
        "category": "SNIPER",
        "damage": 145,
        "fire_rate": 1.10,
        "range_stat": 99,
        "accuracy": 99,
        "mobility": 50,
        "recoil": 70,
        "magazine_size": 6,
        "reload_time": 2.0,
        "ads_speed": 0.32,
        "unlock_level": 50,
        "tier": "BLUEPRINT",
        "description": "The definitive blueprint sniper rifle. Perfectly weighted balance and immediate optic snap.",
        "attachments": ["scope8x", "scope4x", "suppressor", "bipod"],
        "skins": ["Cyber Gold", "Royal Violet"]
    },

    # 6. PISTOLS & SIDEARMS (8)
    {
        "id": "pst_sentinel9",
        "name": "Sentinel-9 Sidearm",
        "category": "PISTOL",
        "damage": 38,
        "fire_rate": 0.18,
        "range_stat": 40,
        "accuracy": 70,
        "mobility": 95,
        "recoil": 35,
        "magazine_size": 12,
        "reload_time": 1.1,
        "ads_speed": 0.12,
        "unlock_level": 1,
        "tier": "COMMON",
        "description": "Precision semi-automatic blueprint sidearm. Clean trigger reset and rapid draw.",
        "attachments": ["iron", "reddot", "suppressor", "extended_mag"],
        "skins": ["Classic Blue", "Charcoal Graphite"]
    },
    {
        "id": "pst_bulldog45",
        "name": "Bulldog-45 Tactical",
        "category": "PISTOL",
        "damage": 46,
        "fire_rate": 0.24,
        "range_stat": 44,
        "accuracy": 68,
        "mobility": 92,
        "recoil": 48,
        "magazine_size": 8,
        "reload_time": 1.2,
        "ads_speed": 0.14,
        "unlock_level": 7,
        "tier": "RARE",
        "description": "Heavy caliber .45 handgun with superior stopping punch per round.",
        "attachments": ["laser_sight", "compensator", "extended_mag"],
        "skins": ["Crimson Rebel", "Classic Blue"]
    },
    {
        "id": "pst_talon_rev",
        "name": "Talon-Revolver .357",
        "category": "PISTOL",
        "damage": 78,
        "fire_rate": 0.45,
        "range_stat": 52,
        "accuracy": 78,
        "mobility": 88,
        "recoil": 72,
        "magazine_size": 6,
        "reload_time": 1.9,
        "ads_speed": 0.16,
        "unlock_level": 13,
        "tier": "RARE",
        "description": "6-shot magnum blueprint cylinder delivering devastating headshot damage.",
        "attachments": ["reddot", "laser_sight"],
        "skins": ["Sepia Parchment", "Cyber Gold"]
    },
    {
        "id": "pst_auto_blueprint",
        "name": "Blueprint Machine Pistol",
        "category": "PISTOL",
        "damage": 22,
        "fire_rate": 0.068,
        "range_stat": 34,
        "accuracy": 56,
        "mobility": 96,
        "recoil": 52,
        "magazine_size": 24,
        "reload_time": 1.3,
        "ads_speed": 0.13,
        "unlock_level": 19,
        "tier": "EPIC",
        "description": "Fully automatic pocket machine pistol discharging blinding bullet storms.",
        "attachments": ["reddot", "suppressor", "extended_mag"],
        "skins": ["Neon Grid", "Classic Blue"]
    },
    {
        "id": "pst_apex19",
        "name": "Apex-19 Combat",
        "category": "PISTOL",
        "damage": 40,
        "fire_rate": 0.17,
        "range_stat": 42,
        "accuracy": 74,
        "mobility": 94,
        "recoil": 32,
        "magazine_size": 15,
        "reload_time": 1.05,
        "ads_speed": 0.11,
        "unlock_level": 25,
        "tier": "RARE",
        "description": "High-capacity polymer framed handgun with ultra-fast tactical reload.",
        "attachments": ["reddot", "compensator", "extended_mag"],
        "skins": ["Charcoal Graphite", "Royal Violet"]
    },
    {
        "id": "pst_dual_enforcers",
        "name": "Dual Akimbo Enforcers",
        "category": "PISTOL",
        "damage": 36,
        "fire_rate": 0.10,
        "range_stat": 32,
        "accuracy": 50,
        "mobility": 90,
        "recoil": 60,
        "magazine_size": 30,
        "reload_time": 1.8,
        "ads_speed": 0.20,
        "unlock_level": 33,
        "tier": "EPIC",
        "description": "Akimbo dual-wield pistols doubling hipfire firepower in close quarters.",
        "attachments": ["laser_sight", "extended_mag"],
        "skins": ["Crimson Rebel", "Cyber Gold"]
    },
    {
        "id": "pst_eclipse_mini",
        "name": "Eclipse-Mini Covert",
        "category": "PISTOL",
        "damage": 42,
        "fire_rate": 0.16,
        "range_stat": 45,
        "accuracy": 76,
        "mobility": 96,
        "recoil": 30,
        "magazine_size": 14,
        "reload_time": 1.0,
        "ads_speed": 0.10,
        "unlock_level": 41,
        "tier": "LEGENDARY",
        "description": "Ultralight covert titanium slide pistol with hair trigger pull.",
        "attachments": ["suppressor", "reddot", "laser_sight"],
        "skins": ["Royal Violet", "Neon Grid"]
    },
    {
        "id": "pst_phantom_gold",
        "name": "Phantom Gold Master",
        "category": "PISTOL",
        "damage": 50,
        "fire_rate": 0.15,
        "range_stat": 48,
        "accuracy": 80,
        "mobility": 95,
        "recoil": 28,
        "magazine_size": 16,
        "reload_time": 0.95,
        "ads_speed": 0.09,
        "unlock_level": 47,
        "tier": "BLUEPRINT",
        "description": "Inscribed golden masterwork pistol with instantaneous optic target acquisition.",
        "attachments": ["reddot", "suppressor", "extended_mag"],
        "skins": ["Cyber Gold", "Classic Blue"]
    },

    # 7. MELEE & TACTICAL (6)
    {
        "id": "melee_knife",
        "name": "Tactical Blueprint Blade",
        "category": "MELEE",
        "damage": 110,
        "fire_rate": 0.38,
        "range_stat": 12,
        "accuracy": 100,
        "mobility": 100,
        "recoil": 0,
        "magazine_size": 1,
        "reload_time": 0.1,
        "ads_speed": 0.05,
        "unlock_level": 1,
        "tier": "COMMON",
        "description": "Sharpened tactical blueprint combat blade. Silent lethal CQB swipe.",
        "attachments": [],
        "skins": ["Classic Blue", "Charcoal Graphite"]
    },
    {
        "id": "melee_karambit",
        "name": "Karambit-Fold Curved",
        "category": "MELEE",
        "damage": 115,
        "fire_rate": 0.32,
        "range_stat": 10,
        "accuracy": 100,
        "mobility": 100,
        "recoil": 0,
        "magazine_size": 1,
        "reload_time": 0.1,
        "ads_speed": 0.05,
        "unlock_level": 9,
        "tier": "RARE",
        "description": "Curved tactical blade allowing fast reverse-grip slashes.",
        "attachments": [],
        "skins": ["Crimson Rebel", "Cyber Gold"]
    },
    {
        "id": "melee_tomahawk",
        "name": "Combat Tomahawk",
        "category": "MELEE",
        "damage": 130,
        "fire_rate": 0.48,
        "range_stat": 14,
        "accuracy": 100,
        "mobility": 96,
        "recoil": 0,
        "magazine_size": 1,
        "reload_time": 0.1,
        "ads_speed": 0.05,
        "unlock_level": 18,
        "tier": "EPIC",
        "description": "Weighted steel combat axe delivering heavy fracturing cleaves.",
        "attachments": [],
        "skins": ["Sepia Parchment", "Charcoal Graphite"]
    },
    {
        "id": "melee_trench",
        "name": "Trench Dagger Spike",
        "category": "MELEE",
        "damage": 120,
        "fire_rate": 0.30,
        "range_stat": 11,
        "accuracy": 100,
        "mobility": 100,
        "recoil": 0,
        "magazine_size": 1,
        "reload_time": 0.1,
        "ads_speed": 0.05,
        "unlock_level": 27,
        "tier": "RARE",
        "description": "Triangular blade designed for rapid thrusts and armor penetration.",
        "attachments": [],
        "skins": ["Classic Blue", "Neon Grid"]
    },
    {
        "id": "melee_katana",
        "name": "Cyber Katana Blueprint",
        "category": "MELEE",
        "damage": 140,
        "fire_rate": 0.42,
        "range_stat": 16,
        "accuracy": 100,
        "mobility": 98,
        "recoil": 0,
        "magazine_size": 1,
        "reload_time": 0.1,
        "ads_speed": 0.05,
        "unlock_level": 35,
        "tier": "LEGENDARY",
        "description": "Folded architectural carbon steel katana with extended reach.",
        "attachments": [],
        "skins": ["Cyber Gold", "Royal Violet"]
    },
    {
        "id": "melee_stun_baton",
        "name": "Shock Baton Enforcer",
        "category": "MELEE",
        "damage": 105,
        "fire_rate": 0.35,
        "range_stat": 13,
        "accuracy": 100,
        "mobility": 98,
        "recoil": 0,
        "magazine_size": 1,
        "reload_time": 0.1,
        "ads_speed": 0.05,
        "unlock_level": 42,
        "tier": "BLUEPRINT",
        "description": "High-voltage riot baton disorienting targets upon physical impact.",
        "attachments": [],
        "skins": ["Neon Grid", "Cyber Gold"]
    }
]

def seed_database():
    init_db()
    db = SessionLocal()
    try:
        # 1. Seed Weapons Catalog
        print(f"Seeding {len(WEAPONS_CATALOG)} tactical weapons into database...")
        for w_data in WEAPONS_CATALOG:
            existing = db.query(Weapon).filter(Weapon.id == w_data["id"]).first()
            if not existing:
                w = Weapon(
                    id=w_data["id"],
                    name=w_data["name"],
                    category=w_data["category"],
                    damage=w_data["damage"],
                    fire_rate=w_data["fire_rate"],
                    range_stat=w_data["range_stat"],
                    accuracy=w_data["accuracy"],
                    mobility=w_data["mobility"],
                    recoil=w_data["recoil"],
                    magazine_size=w_data["magazine_size"],
                    reload_time=w_data["reload_time"],
                    ads_speed=w_data["ads_speed"],
                    unlock_level=w_data["unlock_level"],
                    tier=w_data["tier"],
                    description=w_data["description"],
                    attachments_json=json.dumps(w_data.get("attachments", [])),
                    skins_json=json.dumps(w_data.get("skins", []))
                )
                db.add(w)

        # 2. Seed Demo Admin & Bot Players for Leaderboard & Matchmaking
        print("Seeding demo players and AI squad roster...")
        demo_users = [
            ("alpha@astra.fps", "Alpha_Ghost", "DIAMOND II", 5200, 38, 720.0),
            ("viper@astra.fps", "Viper_Rebel", "PLATINUM III", 4200, 29, 640.0),
            ("cobra@astra.fps", "Cobra_Lead", "GOLD I", 2500, 18, 510.0),
            ("falcon@astra.fps", "Falcon_Point", "MASTER", 6300, 48, 850.0),
            ("shadow@astra.fps", "Shadow_Sniper", "LEGEND", 8200, 65, 940.0)
        ]

        for email, uname, rank, r_score, lvl, skill in demo_users:
            if not db.query(User).filter(User.email == email).first():
                u = User(
                    email=email,
                    password_hash=hash_password("AstraTactical2026!"),
                    is_guest=False
                )
                db.add(u)
                db.flush()

                p = Player(
                    user_id=u.id,
                    username=uname,
                    level=lvl,
                    rank=rank,
                    rank_score=r_score,
                    skill_score=skill,
                    matches=lvl * 4,
                    wins=int(lvl * 2.8),
                    kills=lvl * 22,
                    deaths=lvl * 8,
                    headshots=lvl * 7,
                    damage=lvl * 2600,
                    accuracy=68.5
                )
                db.add(p)
                db.flush()

                ld = Loadout(
                    player_id=p.id,
                    name="Combat Ready",
                    primary_weapon="ar_astra4",
                    secondary_weapon="sg_trench12",
                    is_equipped=True
                )
                db.add(ld)

        db.commit()
        print("[OK] Database seeded successfully with 52 weapons and competitive rosters!")
    except Exception as e:
        db.rollback()
        print(f"Error during seeding: {e}")
        raise
    finally:
        db.close()

if __name__ == "__main__":
    seed_database()
